repos:
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.3.3
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier
          - prettier-plugin-toml
        args:
          - --cache
          - --cache-location=.prettier-cache
          - --ignore-path=.gitignore
        minimum_pre_commit_version: 2.9.0
        types_or:
          - json
          - json5
          - markdown
          - toml
          - yaml
  - repo: meta
    hooks:
      - id: check-hooks-apply
        name: check-hooks-apply
      - id: check-useless-excludes
        name: check-useless-excludes
  - repo: https://github.com/mondeja/project-config
    rev: v0.9.5
    hooks:
      - id: project-config
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        name: trailing-whitespace
      - id: end-of-file-fixer
        name: end-of-file-fixer
      - id: check-added-large-files
        name: check-added-large-files
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.29.1
    hooks:
      - id: check-github-workflows
        name: check-github-workflows
        args:
          - --verbose
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.7.3
    hooks:
      - id: editorconfig-checker
        name: editorconfig-checker
        alias: ec
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
        name: shellcheck
        files: test
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.13.0
    hooks:
      - id: markdownlint-cli2
  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.12.2
    hooks:
      - id: markdown-link-check
        name: markdown-link-check
