repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        name: trailing-whitespace
      - id: end-of-file-fixer
        name: end-of-file-fixer
      - id: check-added-large-files
        name: check-added-large-files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.1
    hooks:
      - id: prettier
        types_or:
          - json5
          - markdown
          - toml
        additional_dependencies:
          - prettier
          - prettier-plugin-toml
  - repo: https://github.com/mondeja/project-config
    rev: v0.7.7
    hooks:
      - id: project-config
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
        name: shellcheck
        files: test
