#!/bin/sh

# Repositories to check

# https://github.com/mondeja/project-config
# https://github.com/mondeja/mdpo

TEMPDIR="/tmp/project-config-styles-tests"

prepareTempdir() {
  if ! [ -d "$TEMPDIR" ]; then
    mkdir "$TEMPDIR"
  fi
  printf '0' > "$TEMPDIR/exitcode.txt"
}

check() {
  grep '^# https://' "$0" | while read -r _ repo directory; do
    dirname="$(basename "$repo")"
    echo "--- $dirname ---"
    dirpath="$TEMPDIR/$dirname"
    set -e
    if [ -d "$dirpath" ]; then
      cd "$dirpath" || exit 1
      git pull > /dev/null
    else
      git clone --depth=1 "$repo" "$dirpath"
    fi
    cd "$TEMPDIR/$dirname" || exit 1
    pre-commit install > /dev/null
    set +e

    project_config_fix_cmd="$(< .pre-commit-config.yaml grep project-config-fix)"
    if [ -n "$project_config_fix_cmd" ]; then
      hook_id="project-config-fix"
    else
      hook_id="project-config"
    fi
    pre-commit run -a "$hook_id"
    if [ "$?" -ne 0 ]; then
      printf '%s' "1" > "$TEMPDIR/exitcode.txt"
    fi
    echo
  done;
}

main() {
  prepareTempdir
  check
  exit "$(cat "$TEMPDIR/exitcode.txt")"
}

main
