#!/bin/sh

# Repositories to check:

# https://github.com/mondeja/project-config
# https://github.com/mondeja/mdpo

TEMPDIR="/tmp/project-config-styles-tests"

prepareTempdir() {
  if ! [ -d "$TEMPDIR" ]; then
    mkdir "$TEMPDIR"
  fi
  printf '0' > "$TEMPDIR/exitcode.txt"
}

check() {
  grep '^# https://' "$0" | while read -r line; do
    set -e
    repo="$(printf %s "$line" | cut -d' ' -f2)"
    dirname="$(basename "$repo")"
    printf "%s\n" "--- $dirname ---"
    dirpath="$TEMPDIR/$dirname"
    if [ -d "$dirpath" ]; then
      cd "$dirpath"
      git pull > /dev/null
    else
      git clone -c protocol.version=2 --depth=1 "$repo" "$dirpath"
    fi
    cd "$TEMPDIR/$dirname"
    pre-commit install > /dev/null

    set +e
    project_config_fix_cmd="$(< .pre-commit-config.yaml grep project-config-fix)"
    if [ -n "$project_config_fix_cmd" ]; then
      hook_id="project-config-fix"
    else
      hook_id="project-config"
    fi
    if ! pre-commit run -a "$hook_id"; then
      printf '%s' "1" > "$TEMPDIR/exitcode.txt"
    fi
    printf "\n"
  done;
}

main() {
  prepareTempdir
  check
  exitcode="$(cat "$TEMPDIR/exitcode.txt")"
  exit "$exitcode"
}

main
