name: Fix repository

on:
  workflow_dispatch:
    inputs:
      repository:
        required: true
        description: Github repository to fix
      version:
        required: false
        description: project-config-styles version used to run project-config fix

jobs:
  fix-repo:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python v3
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install pre-commit pyyaml pyjson5
      - name: Configure GIT
        run: |
          git config --global user.email "mondejar1994@gmail.com"
          git config --global user.name "Álvaro Mondéjar Rubio"
      - name: Run project-config fix
        run: ./_scripts/fix-repo "$REPOSITORY" "$VERSION"
        env:
          REPOSITORY: ${{ github.event.inputs.repository }}
          VERSION: ${{ github.event.inputs.version }}
          GH_TOKEN: ${{ secrets.FIX_REPO_GITHUB_TOKEN }}
