name: pre-commit

permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-python@v5.0.0
        name: Set up Python
        with:
          python-version: 3.x
      - run: pip install pre-commit
      - run: pre-commit run -a
